site_name: OAP Project
theme: null
extra_css: [extra.css]
theme_dir: mkdocs_windmill
repo_name: 'Fork on GitHub '
repo_url: 'https://github.com/oap-project/'
google_analytics: ['UA-125166209-1', 'oap-project.github.io']
extra:
    version: master
    article_nav_top: false
    article_nav_bottom: false



pages:
  - Overview: index.md
  - OAP Installation Guide: OAP-Installation-Guide.md
  - OAP Developer Guide: OAP-Developer-Guide.md




